package com.guanseq;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Map;

import org.yaml.snakeyaml.Yaml;

import org.junit.jupiter.api.Test;

class OpenApiContractTest {

	@Test
	void publishesVersionedPlatformWorkspaceAndMasterDataContracts() throws IOException {
		try (var stream = getClass().getResourceAsStream("/openapi/guanseq-api-v1.yaml")) {
			assertThat(stream).isNotNull();
			String contract = new String(stream.readAllBytes(), StandardCharsets.UTF_8);
			Map<String, Object> parsed = new Yaml().loadAs(contract, Map.class);
			assertThat(parsed).containsKey("openapi");
			assertThat(parsed.get("openapi")).isEqualTo("3.1.0");
			Map<String, Object> components = (Map<String, Object>) parsed.get("components");
			Map<String, Object> securitySchemes = (Map<String, Object>) components.get("securitySchemes");
			Map<String, Object> responses = (Map<String, Object>) components.get("responses");
			Map<String, Object> schemas = (Map<String, Object>) components.get("schemas");
			assertThat(securitySchemes).containsKey("bearerAuth").doesNotContainKey("basicAuth");
			assertThat((Map<String, Object>) securitySchemes.get("bearerAuth"))
					.containsEntry("type", "http")
					.containsEntry("scheme", "bearer")
					.containsEntry("bearerFormat", "JWT");
			assertThat(responses).containsKeys("ValidationFailed", "AuthenticationRequired", "AccessDenied",
					"ResourceNotFound", "BusinessConflict", "BusinessRuleViolation", "InternalError");
			assertThat(schemas).containsKeys("ApiError", "FieldViolation");
			Map<String, Object> purchaseReceipt = (Map<String, Object>) schemas.get("PurchaseReceipt");
			Map<String, Object> purchaseReceiptProperties = (Map<String, Object>) purchaseReceipt.get("properties");
			assertThat((java.util.List<String>) purchaseReceipt.get("required")).contains("source");
			assertThat((Map<String, Object>) purchaseReceiptProperties.get("source"))
					.containsEntry("enum", java.util.List.of("DESKTOP_FORM", "MOBILE_SCAN"));
			Map<String, Object> receiptReferences = (Map<String, Object>) schemas.get("PurchaseReceiptReferenceData");
			assertThat((java.util.List<String>) receiptReferences.get("required")).contains("canCreate");
			Map<String, Object> operationEvent = (Map<String, Object>) schemas.get("OperationTaskEvent");
			assertThat((java.util.List<String>) operationEvent.get("required")).contains("source");
			Map<String, Object> workReport = (Map<String, Object>) schemas.get("ProductionWorkReport");
			Map<String, Object> workReportProperties = (Map<String, Object>) workReport.get("properties");
			assertThat((java.util.List<String>) workReport.get("required")).contains("source");
			assertThat(workReportProperties).containsKeys("operationTaskId", "operationTaskNumber", "source");
			Map<String, Object> salesOrder = (Map<String, Object>) schemas.get("SalesOrder");
			Map<String, Object> salesOrderProperties = (Map<String, Object>) salesOrder.get("properties");
			assertThat((java.util.List<String>) ((Map<String, Object>) salesOrderProperties.get("status")).get("enum"))
					.containsExactly("DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "RELEASED",
							"PARTIALLY_SHIPPED", "SHIPPED", "PARTIALLY_RETURNED", "RETURNED");
			Map<String, Object> salesOrderLine = (Map<String, Object>) schemas.get("SalesOrderLine");
			assertThat((java.util.List<String>) salesOrderLine.get("required"))
					.contains("deliveredQuantity", "returnedQuantity", "netDeliveredQuantity");
			Map<String, Object> receivableReferences = (Map<String, Object>) schemas.get("ReceivableReferenceData");
			Map<String, Object> receivableReferenceProperties = (Map<String, Object>) receivableReferences.get("properties");
			Map<String, Object> receivableOrders = (Map<String, Object>) receivableReferenceProperties.get("orders");
			Map<String, Object> receivableOrderItems = (Map<String, Object>) receivableOrders.get("items");
			Map<String, Object> receivableOrderProperties = (Map<String, Object>) receivableOrderItems.get("properties");
			assertThat((java.util.List<String>) ((Map<String, Object>) receivableOrderProperties.get("orderStatus")).get("enum"))
					.containsExactly("PARTIALLY_SHIPPED", "SHIPPED", "PARTIALLY_RETURNED", "RETURNED");
			assertThat(contract)
					.contains("openapi: 3.1.0")
					.contains("/api/v1/platform/status:")
					.contains("/api/v1/bootstrap/initial-workspace:")
					.contains("/api/v1/identity/workspace-users:")
					.contains("/api/v1/identity/workspace-users/{userId}/actions:")
					.contains("/api/v1/equipment/assets:")
					.contains("/api/v1/equipment/assets/{id}:")
					.contains("/api/v1/equipment/assets/{id}/actions:")
					.contains("/api/v1/equipment/telemetry-connections:")
					.contains("/api/v1/equipment/telemetry-connections/{id}:")
					.contains("/api/v1/equipment/telemetry-connections/{id}/test:")
					.contains("/api/v1/equipment/telemetry-connections/{id}/activate:")
					.contains("/api/v1/equipment/telemetry-connections/{id}/pause:")
					.contains("/api/v1/equipment/telemetry-connections/{id}/poll:")
					.contains("/api/v1/equipment/telemetry-field-acceptances/{connectionId}:")
					.contains("/api/v1/equipment/telemetry-field-acceptances/{connectionId}/actions:")
					.contains("/api/v1/equipment/telemetry-samples:")
					.contains("/api/v1/equipment/telemetry-retention-policy:")
					.contains("/api/v1/equipment/telemetry-retention-policy/cleanup:")
					.contains("/api/v1/equipment/telemetry-retention-policy/automation/run-now:")
					.contains("/api/v1/equipment/telemetry-retention-runs/{id}/acknowledge:")
					.contains("/api/v1/equipment/alert-rules:")
					.contains("/api/v1/equipment/alert-rules/{id}/actions:")
					.contains("/api/v1/equipment/alerts:")
					.contains("/api/v1/equipment/alerts/{id}:")
					.contains("/api/v1/equipment/alerts/{id}/actions:")
					.contains("/api/v1/equipment/oee-records:")
					.contains("/api/v1/equipment/oee-records/{id}:")
					.contains("/api/v1/equipment/oee-records/{id}/actions:")
					.contains("/api/v1/equipment/work-orders:")
					.contains("/api/v1/equipment/work-orders/{id}:")
					.contains("/api/v1/equipment/work-orders/{id}/actions:")
					.contains("/api/v1/equipment/maintenance-plans:")
					.contains("/api/v1/equipment/maintenance-plans/{id}:")
					.contains("/api/v1/equipment/maintenance-plans/{id}/actions:")
					.contains("/api/v1/equipment/maintenance-plans/generate:")
					.contains("/api/v1/me/workspaces:")
					.contains("/api/v1/me/current-workspace:")
					.contains("/api/v1/masterdata/customers:")
					.contains("/api/v1/masterdata/customers/batch:")
					.contains("/api/v1/masterdata/materials:")
					.contains("/api/v1/masterdata/materials/batch:")
					.contains("/api/v1/sales/orders:")
					.contains("/api/v1/sales/orders/{id}/actions:")
					.contains("/api/v1/sales/shipments:")
					.contains("/api/v1/sales/shipments/{id}:")
					.contains("/api/v1/sales/shipment-reference-data:")
					.contains("/api/v1/sales/returns:")
					.contains("/api/v1/sales/returns/{id}:")
					.contains("/api/v1/sales/returns/{id}/actions:")
					.contains("/api/v1/sales/return-reference-data:")
					.contains("/api/v1/procurement/returns:")
					.contains("/api/v1/procurement/returns/{id}:")
					.contains("/api/v1/procurement/returns/{id}/actions:")
					.contains("/api/v1/procurement/return-reference-data:")
					.contains("/api/v1/sales/order-reference-data:")
					.contains("/api/v1/finance/receivable-invoices:")
					.contains("/api/v1/finance/receivable-invoices/{id}/receipts:")
					.contains("/api/v1/finance/receivable-reference-data:")
					.contains("/api/v1/finance/payable-invoices:")
					.contains("/api/v1/finance/payable-invoices/{id}/payments:")
					.contains("/api/v1/finance/payable-reference-data:")
					.contains("/api/v1/finance/work-center-cost-rates:")
					.contains("/api/v1/finance/work-center-cost-rates/{id}/status:")
					.contains("/api/v1/planning/independent-demands:")
					.contains("/api/v1/planning/independent-demands/{id}/actions:")
					.contains("/api/v1/planning/mrp-inputs:")
					.contains("/api/v1/planning/mrp-runs:")
					.contains("/api/v1/planning/mrp-runs/{id}:")
					.contains("/api/v1/planning/mrp-suggestions:")
					.contains("/api/v1/planning/mrp-suggestions/{id}/actions:")
					.contains("/api/v1/planning/mrp-suggestions/{id}/convert:")
					.contains("/api/v1/product/boms:")
					.contains("/api/v1/product/boms/{id}:")
					.contains("/api/v1/product/boms/{id}/actions:")
					.contains("/api/v1/product/bom-reference-data:")
					.contains("/api/v1/product/routings:")
					.contains("/api/v1/product/routings/{id}/actions:")
					.contains("/api/v1/product/routing-reference-data:")
					.contains("/api/v1/warehouse/inventory-balances:")
					.contains("/api/v1/warehouse/inventory-balances/{id}/movements:")
					.contains("/api/v1/warehouse/inventory-reference-data:")
					.contains("/api/v1/warehouse/putaway-reference-data:")
					.contains("/api/v1/warehouse/putaway-tasks:")
					.contains("/api/v1/warehouse/putaway-tasks/{id}/complete:")
					.contains("/api/v1/warehouse/putaway-tasks/{id}/cancel:")
					.contains("/api/v1/warehouse/putaway-tasks/{id}/reverse:")
					.contains("/api/v1/warehouse/inventory-control-reference-data:")
					.contains("/api/v1/warehouse/transfer-tasks:")
					.contains("/api/v1/warehouse/transfer-tasks/{id}/complete:")
					.contains("/api/v1/warehouse/transfer-tasks/{id}/cancel:")
					.contains("/api/v1/warehouse/transfer-tasks/{id}/reverse:")
					.contains("/api/v1/warehouse/stock-count-tasks:")
					.contains("/api/v1/warehouse/stock-count-tasks/{id}/record-count:")
					.contains("/api/v1/warehouse/stock-count-tasks/{id}/approve:")
					.contains("/api/v1/warehouse/stock-count-tasks/{id}/cancel:")
					.contains("/api/v1/warehouse/stock-count-tasks/{id}/reverse:")
					.contains("/api/v1/procurement/orders:")
					.contains("/api/v1/procurement/orders/{id}/actions:")
					.contains("/api/v1/procurement/order-reference-data:")
					.contains("/api/v1/procurement/receipts:")
					.contains("/api/v1/procurement/receipt-reference-data:")
					.contains("/api/v1/production/orders:")
					.contains("/api/v1/production/orders/{id}/actions:")
					.contains("/api/v1/production/operation-labor-entries:")
					.contains("/api/v1/production/operation-labor-entries/{id}/actions:")
					.contains("/api/v1/production/order-reference-data:")
					.contains("/api/v1/production/work-reports:")
					.contains("/api/v1/production/work-reports/{id}/settle:")
				.contains("/api/v1/production/material-issues:")
				.contains("/api/v1/production/material-issues/{id}/actions:")
				.contains("/api/v1/production/material-issues/{id}/returns:")
					.contains("/api/v1/production/material-issue-reference-data:")
					.contains("/api/v1/labeling/reference-data:")
					.contains("/api/v1/labeling/print-requests:")
					.contains("/api/v1/quality/final-inspections:")
					.contains("/api/v1/quality/final-inspections/{id}/complete:")
					.contains("/api/v1/quality/incoming-inspections:")
					.contains("/api/v1/quality/incoming-inspections/{id}/complete:")
					.contains("/api/v1/planning/material-parameters:")
					.contains("X-Request-Id:")
					.contains("PlatformStatus:")
					.contains("InitialWorkspaceBootstrapRequest:")
					.contains("InitialWorkspaceBootstrapResponse:")
					.contains("WorkspaceUserPage:")
					.contains("WorkspaceUserActionRequest:")
					.contains("EquipmentAssetPage:")
					.contains("EquipmentAsset:")
					.contains("EquipmentAssetEvent:")
					.contains("CreateEquipmentAssetRequest:")
					.contains("UpdateEquipmentAssetRequest:")
					.contains("EquipmentAssetActionRequest:")
					.contains("EquipmentTelemetryConnectionPage:")
					.contains("EquipmentTelemetryConnection:")
					.contains("EquipmentTelemetryPoint:")
					.contains("EquipmentTelemetryMqttConfiguration:")
					.contains("CreateEquipmentTelemetryMqttConfigurationRequest:")
					.contains("EquipmentTelemetryCurrentValue:")
					.contains("EquipmentTelemetrySamplePage:")
					.contains("EquipmentTelemetrySample:")
					.contains("EquipmentTelemetryRetentionPolicy:")
					.contains("EquipmentTelemetryRetentionEvent:")
					.contains("EquipmentTelemetryRetentionAutomationRun:")
					.contains("EquipmentTelemetryRetentionAutomationActionResult:")
					.contains("EquipmentTelemetryCleanupResult:")
					.contains("CreateEquipmentTelemetryConnectionRequest:")
					.contains("EquipmentTelemetryActionRequest:")
					.contains("EquipmentTelemetryFieldAcceptanceContext:")
					.contains("EquipmentTelemetryFieldAcceptance:")
					.contains("EquipmentTelemetryFieldAcceptanceEvent:")
					.contains("SaveEquipmentTelemetryFieldAcceptanceRequest:")
					.contains("EquipmentTelemetryFieldAcceptanceActionRequest:")
					.contains("EquipmentAlertRulePage:")
					.contains("EquipmentAlertRule:")
					.contains("EquipmentAlertPage:")
					.contains("EquipmentAlert:")
					.contains("EquipmentAlertActionRequest:")
					.contains("EquipmentOeePage:")
					.contains("EquipmentOeeRecord:")
					.contains("EquipmentOeeDowntime:")
					.contains("EquipmentOeeEvent:")
					.contains("CreateEquipmentOeeRequest:")
					.contains("EquipmentOeeActionRequest:")
					.contains("EquipmentWorkOrderPage:")
					.contains("EquipmentWorkOrder:")
					.contains("EquipmentWorkOrderEvent:")
					.contains("CreateEquipmentWorkOrderRequest:")
					.contains("EquipmentWorkOrderActionRequest:")
					.contains("EquipmentMaintenancePlanPage:")
					.contains("EquipmentMaintenancePlan:")
					.contains("EquipmentMaintenanceGenerationRun:")
					.contains("CreateEquipmentMaintenancePlanRequest:")
					.contains("GenerateEquipmentMaintenanceRequest:")
					.contains("WorkspaceSession:")
					.contains("SwitchWorkspaceRequest:")
					.contains("CustomerPage:")
					.contains("MaterialPage:")
					.contains("MasterDataBatchRequest:")
					.contains("SalesOrder:")
					.contains("SalesShipment:")
					.contains("CreateSalesShipmentRequest:")
					.contains("SalesShipmentReferenceData:")
					.contains("SalesReturnPage:")
					.contains("SalesReturn:")
					.contains("SalesReturnLine:")
					.contains("SalesReturnEvent:")
					.contains("CreateSalesReturnRequest:")
					.contains("SalesReturnActionRequest:")
					.contains("SalesReturnReferenceData:")
					.contains("SalesOrderActionRequest:")
					.contains("SalesOrderReferenceData:")
					.contains("IndependentDemand:")
					.contains("IndependentDemandActionRequest:")
					.contains("PlanningDemandReferenceData:")
					.contains("MrpRun:")
					.contains("MrpDemandSnapshot:")
					.contains("MrpSupplySnapshot:")
					.contains("MrpRunException:")
					.contains("MrpSuggestion:")
					.contains("MrpSuggestionActionRequest:")
					.contains("MrpSuggestionConvertRequest:")
					.contains("CreateMrpRunRequest:");
			assertThat(contract)
					.contains("ReceivableInvoicePage:")
					.contains("ReceivableInvoice:")
					.contains("CreateReceivableInvoiceRequest:")
					.contains("PostReceivableReceiptRequest:")
					.contains("ReceivableReferenceData:")
					.contains("PayableInvoicePage:")
					.contains("PayableInvoice:")
					.contains("CreatePayableInvoiceRequest:")
					.contains("PostPayablePaymentRequest:")
					.contains("PayableReferenceData:")
					.contains("WorkCenterCostRatePage:")
					.contains("WorkCenterCostRate:")
					.contains("CreateWorkCenterCostRateRequest:")
					.contains("ChangeWorkCenterCostRateStatusRequest:")
					.contains("ProductionWorkReport:")
					.contains("CreateProductionWorkReportRequest:")
					.contains("OperationLaborEntryPage:")
					.contains("OperationLaborEntry:")
					.contains("CreateOperationLaborEntryRequest:")
					.contains("OperationLaborEntryActionRequest:")
					.contains("FinalInspection:")
					.contains("CompleteFinalInspectionRequest:");
			assertThat(contract)
					.contains("PurchaseOrderPage:")
					.contains("PurchaseOrderActionRequest:")
					.contains("PurchaseReceiptPage:")
					.contains("CreatePurchaseReceiptRequest:")
					.contains("IncomingInspection:")
					.contains("CompleteIncomingInspectionRequest:")
					.contains("MaterialPlanningParameterPage:")
					.contains("MrpScheduledReceiptSnapshot:");
			assertThat(contract)
					.contains("InventoryPage:")
					.contains("InventoryBalance:")
					.contains("InventoryMovement:")
					.contains("InventoryMovementRequest:")
					.contains("InventoryReferenceData:")
					.contains("WarehousePutawayPage:")
					.contains("WarehousePutawayTask:")
					.contains("WarehousePutawayReferenceData:")
					.contains("CreateWarehousePutawayRequest:")
					.contains("WarehouseInventoryControlReferenceData:")
					.contains("WarehouseTransferPage:")
					.contains("WarehouseTransferTask:")
					.contains("CreateWarehouseTransferRequest:")
					.contains("WarehouseStockCountPage:")
					.contains("WarehouseStockCountTask:")
					.contains("CreateWarehouseStockCountRequest:")
					.contains("RecordWarehouseStockCountRequest:")
					.contains("ApproveWarehouseStockCountRequest:")
				.contains("MaterialIssuePage:")
				.contains("MaterialIssue:")
				.contains("CreateMaterialIssueRequest:")
				.contains("MaterialIssueActionRequest:")
				.contains("MaterialReturnRequest:")
				.contains("MaterialIssueReferenceData:")
					.contains("MaterialIssueAvailableStock:")
					.contains("LabelPrintRequestPage:")
					.contains("LabelPrintRequest:")
					.contains("PrepareLabelPrintRequest:")
					.contains("LabelReferenceData:")
					.contains("LabelCandidate:")
				.contains("source: { type: string, enum: [DESKTOP_FORM, MOBILE_SCAN] }")
				.contains("stockBalanceId: { type: [string, \"null\"], format: uuid }");
			assertThat(contract)
					.contains("BomPage:")
					.contains("BomLine:")
					.contains("BomEvent:")
					.contains("CreateBomRequest:")
					.contains("UpdateBomRequest:")
					.contains("BomActionRequest:")
					.contains("BomReferenceData:");
		}
	}
}

